### ISSUE TITLE
Error in if (ambig > 0.1 && verbose) 

### ISSUE THREAD

**Issue by athulmenon** [functionalgenomics/gDNAx#2]
Hi,

Thank you for this tool!

I was able to run the demo data without any issues with 'LiYu22subsetBAMfiles'.

I tried to load my STAR aligned sorted bam files (3 files) and I am getting the below error. 
gdnax <- gDNAdx(bamfiles, txdb, singleEnd=FALSE, useRMSK=FALSE, verbose=TRUE)

`i Library layout: paired-end, 1 (2x86nt), 2 (2x100nt).
Error in if (ambig > 0.1 && verbose) { : 
  missing value where TRUE/FALSE needed`

Could you please let me know the issue?

Regards,
Athul

**Comment by rcastelo** [comment]
Hi, thanks for reporting this, it looks like a bug. I'm travelling right now and will take me a few days to put my hands on it. In the meantime, could you run the tool with each of the BAM files separately at a time to figure out whether the problem happens with each of the BAM files or with just one of them? That would help me to figure out more quickly what's going on.

Thanks again!

**Comment by athulmenon** [comment]
Thank you for your reply.

Yes I tried using a single bam as below, but got the same error.

`gdnax <- gDNAdx("D:\\test\\ALL.sorted.bam", txdb, singleEnd=FALSE, useRMSK=FALSE, verbose=TRUE)`

`i Library layout: paired-end, 1 (2x100nt).
Error in if (ambig > 0.1 && verbose) { : 
  missing value where TRUE/FALSE needed`

Regards,
Athul

**Comment by rcastelo** [comment]
Thanks, would it be possible to have access to this BAM file to allow me reproducing the error?

**Comment by athulmenon** [comment]
Hi,

Thank you for your reply.

Here is the bam file - https://tinyurl.com/mryxtrfe

Regards,
Athul

**Comment by rcastelo** [comment]
Great, thanks, I have successfully downloaded it. I'll write you back here once I can figure out what the problem is and how to fix it.

**Comment by rcastelo** [comment]
Dear @athulmenon thanks for your patience. I identified the problem, related to the fact that chromosome sequences in your BAM file followed an NCBI style (1, 2, 3, ..., X, Y, MT), while the annotations were UCSC (chr1, chr2, chr3, ..., chrX, chrY, chrM), and the automatic matching of both styles was not properly configured. I have submitted a bugfix to both, the development and the RELEASE 3.19 branches of the software tagged with versions 1.3.1 and 1.2.1, respectively. They will become available for update from the Bioconductor repo via `BiocManager::install()` in the next 24 to 48 hours, but you can immediately update your release version of the software through the GitHub repo as follows:

```r
BiocManager::install("rcastelo/gDNAx", ref="RELEASE_3_19")
```

**Comment by athulmenon** [comment]
Thank you! It works!
